version = 0.1

[default.deploy.parameters]
stack_name = "casepacket"
resolve_s3 = true
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EnableBedrock=0"
image_repositories = []
